analyzer:
  exclude:
    - build/**
    - android/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    use_build_context_synchronously: false
